import type { ChildrenType } from "@/@types";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providres from "@/provider";
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Admin Crm Login",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: ChildrenType) => {
  return (
    <Providres>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} antialiased`}>{children}</body>
      </html>
    </Providres>
  );
};

export default AuthLayout;